
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-agent
  labels:
      type: stateful-service-ctmag-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      type: stateful-service-ctmag-srv
  serviceName: "statefulset-agent"
  template:
    metadata:
      labels:
        type: stateful-service-ctmag-srv
    spec:
      containers:
        - name: ctmagent-container
          image: 623469066856.dkr.ecr.us-east-2.amazonaws.com/ctm-agent-image:latest
          env:
          - name: PERSISTENT_VOL
            value: "/home/controlm/persistent_folder"
          - name: AAPI_END_POINT
            value: "https://<UPDATE>:8443/automation-api"
          - name: AAPI_USER
            value: "user"
          - name: AAPI_PASS
            value: "password"
            # user's password, will be present in the logs! consider using k8s secret

          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: pv-data
              mountPath: //home/controlm/persistent_folder
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      volumes:
        - name: pv-data
          persistentVolumeClaim:
              claimName: agent-pvc
